### ISSUE TITLE
Calceph download moved

### ISSUE THREAD

**Issue by nategarver-daniels** [nanograv/nanodocker#8]
Won't affect people who already have the base image built, but today we were builidng an image and noticed that the tgz wasn't in the same place anymore.  I had to change the Docerfile line that pulls calceph to 

wget --no-check-certificate -q https://www.imcce.fr/content/medias/recherche/equipes/asd/calceph/calceph-2.3.2.tar.gz

as they now force https _and_ have an invalid certificate.

**Comment by vallis** [comment]
Fixed in eb2d0e
